# name: try
# key: try
# --
try {
		$0
}
catch (${1:System.Exception}) {
		throw;
}