# name: try
# key: try
# --
try
    $1
catch
    ${2:_:_} -> ${0:got_some_exception}
end